# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
name: $(Rev:rr)

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  displayName: Generate SDK Code from JAR
  enabled: false
  inputs:
    script: |
      echo Generate Code START
      java -jar /home/vsts/work/1/s/executables/swagger-codegen-cli.jar generate \
        -i $(SWAGGER) \
        -l python \
        -o /var/tmp/python_api_client
      echo Generate Code END
- task: CmdLine@2
  displayName: Update Build Version
  inputs:
    script: |
      echo Generate Code START
      sed -i 's/1.0.0/$(VERSION)/g' $(System.DefaultWorkingDirectory)/config.json
      cat $(System.DefaultWorkingDirectory)/config.json
- task: Maven@4
  displayName: Maven package the SDK Code Generator
  inputs:
    mavenPomFile: 'pom.xml'
    options: 'clean -Dmaven.test.skip=true'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CmdLine@2
  displayName: Generate SDK Code from build package
  inputs:
    script: |
      echo Generate Code START
      java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
        -i https://petstore.swagger.io/v2/swagger.json \
        -l python \
        -o $(System.DefaultWorkingDirectory)/output \
        -c config.json
      echo Generate Code END

- task: CmdLine@2
  displayName: Publish Python SDK to repository
  inputs:
    script: |
      echo $(token1)
      cd $(System.DefaultWorkingDirectory)/output
      pip install twine
      python setup.py sdist bdist_wheel
      python -m twine upload -u __token__ -p $(token1) --repository-url https://test.pypi.org/legacy/ dist/* --verbose